language: scala

notifications:
  email:
    on_success: never

# See 'project/Version.scala'
scala:
   - 2.11.6

sbt_args: -no-colors -J-Xss2m

script:
   - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts  test

jdk:
  - oraclejdk8

before_install:
  - sudo add-apt-repository ppa:pgavin/ghdl -y
  - sudo apt-get update
  - sudo apt-get install ghdl -y

# after_success:
# Push to sonatype ?