language: scala

notifications:
  email:
    on_success: never

# See 'project/Version.scala'
scala:
   - 2.11.6

sbt_args: -no-colors -J-Xss2m

script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test test

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  # JDK fix
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

  # GHDL
  - sudo add-apt-repository -y ppa:pgavin/ghdl
  - sudo apt-get update
  - sudo apt-get install -y ghdl

  # iverilog (debian package 9.7 contain bugs)
  - cd ..
  - wget ftp://ftp.icarus.com/pub/eda/verilog/v10/verilog-10.0.tar.gz
  - tar -xvf verilog-10.0.tar.gz
  - cd verilog-10.0
  - ./configure
  - make -j4
  - sudo make install
  - cd ../SpinalHDL

  # cocotb
  - sudo apt-get install -y git make gcc g++ swig python-dev
  - git clone https://github.com/potentialventures/cocotb
  - export COCOTB=$(pwd)/cocotb

  # Force cocotb to compile VPI to avoid race condition when tests are start in parallel
  - cd tester/src/test/python/spinal/BundleTester
  - make
  - cd ../../../../../..

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
