language: scala

notifications:
  email:
    on_success: never

# See 'project/Version.scala'
scala:
   - 2.11.6

sbt_args: -no-colors -J-Xss2m

script:
   - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts  test

jdk:
  - openjdk7

# after_success:
# Push to sonatype ?