name: Scala CI

on:
  push:
    branches: [ gitaction ]
  pull_request:
    branches: [ gitaction ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Tools cache
      id: tools
      uses: actions/cache@v2
      with:
        path: |
          ~/tools
        key: ${{ runner.os }}-tools

    - name: Install tools
      #if: steps.tools.outputs.cache-hit != 'true'
      run: source tools.sh && cd ~/ && install_tools

    - name: Run tests
      run: export PATH=~/tools/bin:$PATH && echo miaou
