name: Scala CI

on:
  push:
    branches: [ gitaction ]
  pull_request:
    branches: [ gitaction ]

jobs:
  enforce-timeout-minutes:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Tools cache
      id: tools
      uses: actions/cache@v2
      with:
        path: |
          ~/tools
        key: ${{ runner.os }}-tools

    - name: Env setup
      run: export PATH=~/tools/bin:$PATH

    - name: Install tools
      if: steps.tools.outputs.cache-hit != 'true'
      run: source tools.sh && (cd ~/ && install_tools) && purge_cocotb

    - name: Fixup
      run: source tools.sh && cd ~/ && (cd ~/ && install_cocotb)  && purge_cocotb

    - name: Compile tests
      run: ls #&& sbt test:compile

    - name: Run tests
      run: ls #&& sbt test
